### ISSUE TITLE
Some comments

### ISSUE THREAD

**Issue by lecorguille** [eosc-life/WP2_workshop_tool_packaging#2]
There are just some comments on. It's up to you to take them into account :)

@sunyi000, about the [CellProfiler](https://github.com/eosc-life/WP2_workshop_tool_packaging/blob/master/CellProfiler/CellProfiler.md)

 - As far as I know, `  script: "{{ PYTHON }} -m pip install --no-deps --ignore-installed . -vv"` isn't used in most the case. More often, there is a `build.sh` script shiped with the `meta.yml`. Just maybe mention that somewhere !?
 - It would be intersting to add a bio.tools identifier https://bio.tools/CellProfiler like we can have in [cutadapt for example]( https://github.com/bioconda/bioconda-recipes/blob/master/recipes/cutadapt/meta.yaml#L41-L44)
 - In [contributing-your-recipe-to-bioconda](https://github.com/eosc-life/WP2_workshop_tool_packaging/blob/master/CellProfiler/CellProfiler.md#contributing-your-recipe-to-bioconda), you miss a link to the [Bioconda guidelines](https://bioconda.github.io/contributor/guidelines.html)

Otherwise, good job :+1:

**Comment by sunyi000** [comment]
Thanks @lecorguille, I have incorporated all your suggestions into the tutorials
